# Generated by Django 5.1.4 on 2025-06-23 13:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id_historique', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('connexion', 'Connexion'), ('deconnexion', 'Déconnexion'), ('reservation', 'Réservation'), ('paiement', 'Paiement'), ('annulation', 'Annulation'), ('validation', 'Validation'), ('rejet', 'Rejet'), ('message', 'Message'), ('avis', 'Avis'), ('upload', 'Upload'), ('export', 'Export'), ('recherche', 'Recherche'), ('autre', 'Autre')], default='autre', max_length=50, verbose_name='Action')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name="ID de l'objet")),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('contexte', models.JSONField(blank=True, help_text='Données supplémentaires au format JSON', null=True, verbose_name='Contexte JSON')),
                ('niveau_importance', models.CharField(choices=[('info', 'Information'), ('attention', 'Attention'), ('critique', 'Critique'), ('securite', 'Sécurité')], default='info', max_length=20, verbose_name="Niveau d'importance")),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, help_text='Informations du navigateur/client', verbose_name='User Agent')),
                ('donnees_avant', models.JSONField(blank=True, help_text="État de l'objet avant modification", null=True, verbose_name='Données avant modification')),
                ('donnees_apres', models.JSONField(blank=True, help_text="État de l'objet après modification", null=True, verbose_name='Données après modification')),
                ('tags', models.CharField(blank=True, help_text='Tags séparés par des virgules pour faciliter la recherche', max_length=500, verbose_name='Tags')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name="Type d'objet concerné")),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques', to=settings.AUTH_USER_MODEL, verbose_name="Utilisateur ayant effectué l'action")),
            ],
            options={
                'verbose_name': 'Historique',
                'verbose_name_plural': 'Historiques',
                'db_table': 'tabali_historiques',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['action'], name='tabali_hist_action_b459ff_idx'), models.Index(fields=['utilisateur'], name='tabali_hist_utilisa_de03e2_idx'), models.Index(fields=['content_type', 'object_id'], name='tabali_hist_content_93cfbd_idx'), models.Index(fields=['-date'], name='tabali_hist_date_160311_idx'), models.Index(fields=['niveau_importance'], name='tabali_hist_niveau__97d8a4_idx'), models.Index(fields=['adresse_ip'], name='tabali_hist_adresse_d22168_idx')],
            },
        ),
    ]
