# Generated by Django 5.1.4 on 2025-06-23 13:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id_paiement', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('echec', 'Échec'), ('rembourse', 'Remboursé'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('methode', models.CharField(choices=[('carte', 'Carte bancaire'), ('virement', 'Virement'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('especes', 'Espèces')], default='carte', max_length=20, verbose_name='Méthode de paiement')),
                ('date_paiement', models.DateTimeField(auto_now_add=True, verbose_name='Date de paiement')),
                ('transaction_id', models.CharField(blank=True, help_text='ID de la transaction Stripe/PayPal/etc.', max_length=255, verbose_name='ID Transaction externe')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='reservations.reservation', verbose_name='Réservation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur payeur')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'tabali_paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id_facture', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_facture', models.CharField(help_text='Numéro unique de la facture', max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date de la facture')),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant total')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('payee', 'Payée'), ('en_retard', 'En retard'), ('annulee', 'Annulée')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, verbose_name='Description des services')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Taux TVA (%)')),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant HT')),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant TVA')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='reservations.reservation', verbose_name='Réservation')),
                ('paiement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facture', to='billing.paiement', verbose_name='Paiement associé')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'tabali_factures',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['statut'], name='tabali_paie_statut_f20aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['methode'], name='tabali_paie_methode_6da3b0_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['reservation'], name='tabali_paie_reserva_310819_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['utilisateur'], name='tabali_paie_utilisa_42c9c5_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['-date_paiement'], name='tabali_paie_date_pa_1ac469_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['numero_facture'], name='tabali_fact_numero__de710a_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['statut'], name='tabali_fact_statut_b09c50_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['date'], name='tabali_fact_date_c09f0f_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['date_echeance'], name='tabali_fact_date_ec_ea97a2_idx'),
        ),
    ]
