# Generated by Django 5.1.4 on 2025-06-23 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateTimeField(verbose_name='Date et heure prévues')),
                ('estimated_duration', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Durée estimée (heures)')),
                ('service_address', models.TextField(verbose_name="Adresse d'intervention")),
                ('service_latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('service_longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('description', models.TextField(verbose_name='Description du problème')),
                ('priority', models.CharField(choices=[('low', 'Normale'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='low', max_length=20, verbose_name='Priorité')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix estimé')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix final')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('cancelled_by_provider', 'Annulée par le prestataire')], default='pending', max_length=30, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation")),
                ('cancellation_reason', models.TextField(blank=True, verbose_name="Raison d'annulation")),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Annulé par')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='accounts.clientprofile', verbose_name='Client')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='accounts.providerprofile', verbose_name='Prestataire')),
                ('provider_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='services.providerservice', verbose_name='Service du prestataire')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'db_table': 'tabali_reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='reservations/photos/', verbose_name='Photo')),
                ('photo_type', models.CharField(choices=[('before', 'Avant intervention'), ('after', 'Après intervention'), ('problem', 'Problème identifié'), ('solution', 'Solution appliquée'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Type de photo')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reservations.reservation', verbose_name='Réservation')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL, verbose_name='Téléchargé par')),
            ],
            options={
                'verbose_name': 'Photo de réservation',
                'verbose_name_plural': 'Photos de réservations',
                'db_table': 'tabali_reservation_photos',
                'ordering': ['photo_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('cancelled_by_provider', 'Annulée par le prestataire')], max_length=30, null=True, verbose_name='Ancien statut')),
                ('new_status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('cancelled_by_provider', 'Annulée par le prestataire')], max_length=30, verbose_name='Nouveau statut')),
                ('reason', models.TextField(blank=True, verbose_name='Raison du changement')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='reservations.reservation', verbose_name='Réservation')),
            ],
            options={
                'verbose_name': 'Historique de statut',
                'verbose_name_plural': 'Historiques de statut',
                'db_table': 'tabali_reservation_status_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['client'], name='tabali_rese_client__d51d4a_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['provider'], name='tabali_rese_provide_e203dd_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status'], name='tabali_rese_status_bc0645_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['scheduled_date'], name='tabali_rese_schedul_c8429c_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['priority'], name='tabali_rese_priorit_6351df_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['-created_at'], name='tabali_rese_created_45c84e_idx'),
        ),
    ]
