# Generated by Django 5.1.4 on 2025-06-23 13:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteAvis',
            fields=[
                ('id_note', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commentaire', models.TextField(help_text='Avis détaillé sur la prestation', verbose_name='Commentaire')),
                ('note', models.IntegerField(help_text='Note de 1 à 5 étoiles', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('date_note', models.DateTimeField(auto_now_add=True, verbose_name='Date de la note')),
                ('type_avis', models.CharField(choices=[('client_prestataire', 'Client vers Prestataire'), ('prestataire_client', 'Prestataire vers Client')], default='client_prestataire', max_length=30, verbose_name="Type d'avis")),
                ('est_visible', models.BooleanField(default=True, verbose_name='Visible publiquement')),
                ('est_modere', models.BooleanField(default=False, verbose_name='Modéré')),
                ('raison_moderation', models.TextField(blank=True, help_text='Pourquoi cet avis a été modéré', verbose_name='Raison de la modération')),
                ('reponse', models.TextField(blank=True, help_text="Réponse optionnelle du prestataire à l'avis", verbose_name='Réponse du prestataire')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de la réponse')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_donnes', to=settings.AUTH_USER_MODEL, verbose_name="Auteur de l'avis")),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_recus', to=settings.AUTH_USER_MODEL, verbose_name="Destinataire de l'avis")),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='reservations.reservation', verbose_name='Réservation concernée')),
            ],
            options={
                'verbose_name': 'Note et Avis',
                'verbose_name_plural': 'Notes et Avis',
                'db_table': 'tabali_notes_avis',
                'ordering': ['-date_note'],
                'indexes': [models.Index(fields=['note'], name='tabali_note_note_cffc3b_idx'), models.Index(fields=['type_avis'], name='tabali_note_type_av_2c6a86_idx'), models.Index(fields=['destinataire'], name='tabali_note_destina_e66f0b_idx'), models.Index(fields=['reservation'], name='tabali_note_reserva_f5f1e3_idx'), models.Index(fields=['-date_note'], name='tabali_note_date_no_6aa089_idx'), models.Index(fields=['est_visible'], name='tabali_note_est_vis_bae2d2_idx')],
                'unique_together': {('reservation', 'auteur', 'type_avis')},
            },
        ),
    ]
