# Generated by Django 5.1.4 on 2025-06-23 13:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvoiMail',
            fields=[
                ('id_emails', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sujet', models.CharField(max_length=255, verbose_name='Sujet')),
                ('contenu', models.TextField(verbose_name="Contenu de l'email")),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('envoye', 'Envoyé'), ('delivre', 'Délivré'), ('ouvert', 'Ouvert'), ('echec', 'Échec'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('email_destinataire', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email destinataire')),
                ('nom_destinataire', models.CharField(blank=True, max_length=255, verbose_name='Nom destinataire')),
                ('type_email', models.CharField(choices=[('confirmation', 'Confirmation'), ('notification', 'Notification'), ('marketing', 'Marketing'), ('facture', 'Facture'), ('rappel', 'Rappel'), ('bienvenue', 'Bienvenue'), ('mot_de_passe', 'Mot de passe')], default='notification', max_length=20, verbose_name="Type d'email")),
                ('date_ouverture', models.DateTimeField(blank=True, null=True, verbose_name="Date d'ouverture")),
                ('nb_ouvertures', models.PositiveIntegerField(default=0, verbose_name="Nombre d'ouvertures")),
                ('erreur_envoi', models.TextField(blank=True, help_text="Détails de l'erreur en cas d'échec", verbose_name="Erreur d'envoi")),
                ('id_externe', models.CharField(blank=True, help_text="ID du service d'envoi d'email externe", max_length=255, verbose_name='ID externe')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_recus', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur destinataire')),
            ],
            options={
                'verbose_name': "Envoi d'email",
                'verbose_name_plural': "Envois d'emails",
                'db_table': 'tabali_envoi_mails',
                'ordering': ['-date_envoi'],
                'indexes': [models.Index(fields=['email_destinataire'], name='tabali_envo_email_d_b9f107_idx'), models.Index(fields=['statut'], name='tabali_envo_statut_7d5ff2_idx'), models.Index(fields=['type_email'], name='tabali_envo_type_em_ca6fa3_idx'), models.Index(fields=['-date_envoi'], name='tabali_envo_date_en_a8d01e_idx'), models.Index(fields=['utilisateur'], name='tabali_envo_utilisa_840b07_idx')],
            },
        ),
        migrations.CreateModel(
            name='Messagerie',
            fields=[
                ('id_messagerie', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenu', models.TextField(verbose_name='Contenu du message')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('delivre', 'Délivré'), ('lu', 'Lu'), ('archive', 'Archivé')], default='envoye', max_length=20, verbose_name='Statut')),
                ('conversation_id', models.UUIDField(default=uuid.uuid4, help_text="Identifiant unique pour grouper les messages d'une conversation", verbose_name='ID Conversation')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='messages/attachments/', verbose_name='Fichier joint')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='reservations.reservation', verbose_name='Réservation concernée')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'tabali_messageries',
                'ordering': ['-date_envoi'],
                'indexes': [models.Index(fields=['conversation_id'], name='tabali_mess_convers_2883d7_idx'), models.Index(fields=['expediteur'], name='tabali_mess_expedit_193e5f_idx'), models.Index(fields=['destinataire'], name='tabali_mess_destina_8675d9_idx'), models.Index(fields=['statut'], name='tabali_mess_statut_cdf851_idx'), models.Index(fields=['-date_envoi'], name='tabali_mess_date_en_54c076_idx'), models.Index(fields=['reservation'], name='tabali_mess_reserva_8a2f29_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenu', models.TextField(verbose_name='Contenu de la notification')),
                ('statut', models.CharField(choices=[('non_lue', 'Non lue'), ('lue', 'Lue'), ('archivee', 'Archivée')], default='non_lue', max_length=20, verbose_name='Statut')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('type_notification', models.CharField(choices=[('reservation', 'Réservation'), ('paiement', 'Paiement'), ('message', 'Message'), ('avis', 'Avis'), ('rappel', 'Rappel'), ('promotion', 'Promotion'), ('systeme', 'Système')], default='systeme', max_length=20, verbose_name='Type de notification')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('lien_action', models.URLField(blank=True, help_text="URL vers laquelle rediriger l'utilisateur", verbose_name="Lien d'action")),
                ('objet_lie_type', models.CharField(blank=True, help_text="Type de l'objet lié (reservation, paiement, etc.)", max_length=50, verbose_name="Type d'objet lié")),
                ('objet_lie_id', models.CharField(blank=True, help_text="ID de l'objet concerné par la notification", max_length=100, verbose_name="ID de l'objet lié")),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'tabali_notifications',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['utilisateur'], name='tabali_noti_utilisa_83a8b7_idx'), models.Index(fields=['statut'], name='tabali_noti_statut_d45de5_idx'), models.Index(fields=['type_notification'], name='tabali_noti_type_no_038e62_idx'), models.Index(fields=['-date'], name='tabali_noti_date_32b175_idx'), models.Index(fields=['objet_lie_type', 'objet_lie_id'], name='tabali_noti_objet_l_40dc3a_idx')],
            },
        ),
    ]
